name: Update Bitcoin Clock (Kindle)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "*/1 * * * *"

permissions:
  contents: write
  
# Added this blank line to force refresh
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate HTML
        run: |
          python3 render.py

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update index.html $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
            git push
          fi
